# DESAFIO 111
# ESTRUTURA MÓDULOS

# CRIE UM PACOTE CHAMADO UTILIDADES_CURSO_EM_VIDEO
# QUE TENHA DOIS MÓDULOS INTERNOS CHAMADOS MOEDA E DADO
# TRANSFIRA TODAS AS FUNÇÕES UTILIZADAS NOS DESAFIOS 107, 108, 109
# PARA O PRIMEIRO PACOTE E MANTENHA TUDO FUNCIONANDO


#IMPORTAÇÕES
from utlidades_curso_em_video.moeda import moeda
# PROGRAMA PRINCIPAL
numero = float(input('Digite o preço em R$: '))
moeda.resumo(numero, 80, 35)
