# TUPLAS (OU VARIÁVEIS COMPOSTAS)

# EXISTEM TRÊS TIPOS DE VARIÁVEIS COMPOSTAS
# AS TUPLAS
# AS LISTAS
# E OS DICIONÁRIOS

# UMA LISTA SE ASSEMELHA COM UMA LISTA
# PORÉM NA LISTA PODEMOS FAZER "COISAS" A MAIS

# --- TEORIA ---

# AS VARIÁVEIS SIMPLES SÃO CAPAZES DE ARMAZENAR APENAS UMA INFORMAÇÃO NO ESPAÇO RESERVADO DA MEMÓRIA
# AS VARIÁVEIS COMPOSTAS SÃO CAPAZES DE ARMAZENAR QUANTOS ESPAÇOS FOREM NECESSÁRIOS

# AS TUPLAS SÃO VARIÁVEIS COMPOSTAS QUE ARMAZENAM QUANTOS VALORES O PROGRAMADOR DECLARAR
# OS VALORES ARMAZENADOS SÃO ACESSADOS POR MEIO DE ÍNDICES
# NO CASO DO PYTHON ESSES ÍNDICES COMEÇAM NO ZERO (0)
# UMA STRING É UMA VARIÁVEL COMPOSTA

# RELEMBRANDO O FATIAMENTO DE STRING
# EXEMPLOS COMENTANDOS
"""
print(lanche)
# O RETORNO SERÁ TODOS OS ELEMENTOS

print(lanche[2])
# O RETORNO SERÁ O ELEMENTO DA POSIÇÃO 3

print(lanche[0:2])
# O RETORNO SERÁ OS ELEMENTOS DA POSIÇÃO 0 E 1
# LEMBRANDO QUE O FATIAMENTO EXCLUÍ A ÚLTIMA POSIÇÃO

print(lanche[1:])
# O RETORNO SERÁ TODOS OS ELEMENTOS A PARTIR DO SEGUNDO (POSIÇÃO 1)

print(lanche[-1])
# O RETORNO SERÁ O ÚLTIMO ELEMENTO
# QUANTO MAIOR O NÚMERO NEGATIVO, MAIS ELE VAI VOLTANDO NA VARIÁVEL

len(lanche)
# O RETORNO SERÁ O TAMANHO DA VARIÁVEL LANCHE, OU SEJA, 5

for comida in lanche:
    print(c)
# O RETORNO SERÁ OS PRINTS DE CADA LANCHE QUE FOR COMIDA

# *** AS TUPLAS SÃO IMUTÁVEIS *** """

# --- PRÁTICA ---
# NO PYTHON COMO HÁ 3 TIPOS DE VARIÁVEIS COMPOSTAS
# PARENTESES PARA TUPLAS
# COLCHETES PARA LISTA
# CHAVES PARA DICIONÁRIO

lanche = ('Hamburguer', 'Suco', 'Pizza', 'Pudim')

# PODE-SE CRIAR UMA TUPLA SEM ADICIONAR OS PARENTESES

# FORMA HABITUAL QUE FAZEMOS PRA MOSTRAR OS ELEMENTOS
# for comida in lanche:
#    print(f'Eu vou comer {comida}')

# FORMA DE SE MOSTRAR OS ELEMENTOS E SUAS POSIÇÕES
# for cont in range(0, len(lanche)):
#    print(f'Eu vou comer {lanche[cont]} na posição {cont}')

# OUTRA FORMA DE SE MOSTRAR OS ELEMENTOS E SUAS POSIÇÕES
for pos, comida in enumerate(lanche):
    print(f'Eu vou comer {comida} na posição {pos}')
print('Comi pra caramba...')

# TAMBÉM PODE-SE USAR O SORTED PARA PRINTAR UMA LISTA
print(sorted(lanche))
# NA VISUALIZAÇÃO DO PRINT, ELE COLOCOU EM ORDEM,
# MAS PARA ISSO ELE PEGOU A TUPLA E COLOCOU COMO LISTA USANDO OS COLCHETES
# VOCÊ PODE "SOMAR" AS TUPLAS
# NA VERDADE A SOMA É A JUNÇÃO DAS TUPLAS
# AS ORDEM DA SOMA DOS ELEMENTOS INFLUÊNCIA
# HÁ ALGUNS ATRIBUTOS QUE PODE-SE USAR
# O COUNT VAI CONTAR OS ELEMENTOS EXISTENTES
# O INDEX VAI MOSTRAR A POSIÇÃO DO ELEMENTO
# PODE DELETAR UMA TUPLA
# USANDO O DEL, PORÉM O DELETE APAGA A TUPLA TODA
# NÃO PODE USAR O DEL COM POSIÇÃO
